AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for bare minimum hydro-processing instance

Parameters:
  KeyPairName:
    Description: sshkey
    Type: String
    Default: oregon_ec2
  LatestAmiId:
    Description: Amazon Linux 2023 AMI
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-minimal-kernel-default-x86_64'

Resources:
  HydroInstance:
    Type: AWS::EC2::Instance
    DeletionPolicy: Retain
    Properties:
      AvailabilityZone: us-west-2a
      InstanceType: 't3.xlarge'
      ImageId: !Ref LatestAmiId
      KeyName: !Ref KeyPairName
      SubnetId: subnet-0d635bac7aecd4c5c
      SecurityGroupIds:
        - sg-0b61f746e5821b972
        - sg-0174195ff9ac497d3
        - sg-07ffd2f10de3a5f4e
      Tags:
        - Key: Name
          Value: hydroOpsProc1
        - Key: group
          Value: wrfHydroOps
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sleep 30
          mkfs -t ext4 /dev/xvdf
          mkdir /data
          mount /dev/xvdf /data
  HydroEBSVolume1:
    Type: AWS::EC2::Volume
    Properties:
      Size: 5000
      VolumeType: gp3
      AvailabilityZone: us-west-2a
  HydroVoumeAttachment1:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !Ref HydroInstance
      VolumeId: !Ref HydroEBSVolume1
      Device: /dev/xvdf